-- MySQL Script generated by MySQL Workbench
-- Sat Apr 23 15:29:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dassai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dassai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dassai` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dassai` ;

-- -----------------------------------------------------
-- Table `dassai`.`question_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`question_groups` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dassai`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`questions` (
  `id` INT NOT NULL,
  `question_group_id` INT NOT NULL,
  `text` VARCHAR(200) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`, `question_group_id`),
  INDEX `qg-q-fk_idx` (`question_group_id` ASC) VISIBLE,
  CONSTRAINT `qg-q-fk`
    FOREIGN KEY (`question_group_id`)
    REFERENCES `dassai`.`question_groups` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dassai`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`answers` (
  `id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `text` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `q-a-fk_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `q-a-fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `dassai`.`questions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dassai`.`question_group_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`question_group_results` (
  `id` INT NOT NULL,
  `question_group_id` INT NOT NULL,
  `text` VARCHAR(45) NULL DEFAULT NULL,
  `redirect_url` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `qgr-qg-fk_idx` (`question_group_id` ASC) VISIBLE,
  CONSTRAINT `qgr-qg-fk`
    FOREIGN KEY (`question_group_id`)
    REFERENCES `dassai`.`question_groups` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dassai`.`answer_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`answer_results` (
  `answer_id` INT NOT NULL,
  `next_question_id` INT NULL DEFAULT NULL,
  `question_result_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `ar-next_q-fk_idx` (`next_question_id` ASC) VISIBLE,
  INDEX `ar-qr-fk_idx` (`question_result_id` ASC) VISIBLE,
  UNIQUE INDEX `answer_id_UNIQUE` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `ar-a-fk`
    FOREIGN KEY (`answer_id`)
    REFERENCES `dassai`.`answers` (`id`),
  CONSTRAINT `ar-next_q-fk`
    FOREIGN KEY (`next_question_id`)
    REFERENCES `dassai`.`questions` (`id`),
  CONSTRAINT `ar-qgr-fk`
    FOREIGN KEY (`question_result_id`)
    REFERENCES `dassai`.`question_group_results` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dassai`.`user_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`user_answers` (
  `id` INT NOT NULL,
  `question_group_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ua-qg-fk_idx` (`question_group_id` ASC) VISIBLE,
  CONSTRAINT `ua-qg-fk`
    FOREIGN KEY (`question_group_id`)
    REFERENCES `dassai`.`question_groups` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dassai`.`user_question_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dassai`.`user_question_answers` (
  `user_answer_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `text` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`user_answer_id`, `question_id`),
  INDEX `uqa-q-fk_idx` (`question_id` ASC) VISIBLE,
  INDEX `answer_id_idx` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `dassai`.`answers` (`id`),
  CONSTRAINT `uqa-q-fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `dassai`.`questions` (`id`),
  CONSTRAINT `uqa-ua-fk`
    FOREIGN KEY (`user_answer_id`)
    REFERENCES `dassai`.`user_answers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
